# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a7215bfa7c62a8b9d28024cbdcc54b937041b57f014bd78cee2e9a5ac4fb30ab74075f34006913464d4378292d0de02792f52582cc666668046e57a6897f9f4e

test:
  secret_key_base: bc25f19a13bbbc6ad4bb889c03395297a25ef2f5bc7699504b3ef53a08c1afd6c65b75df15bce5746dff7cbf8335be68bc70199928ea8c903c28f2e69e57888e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
